[package]
name = "rust_surf"
version = "0.1.0"
authors = ["sufyan arain <sufyan822@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1"
surf = "1"
futures = "0.3.1"
